export const media = {
 xs: `(min-width: 0`,
 sm: `(min-width: 0`,
 md: `(min-width: 0`,
 lg: `(min-width: 0`,
 xl: `(min-width: 0`,
 xsMin: `(min-width: 0`,
 smMin: `(min-width: 0`,
 mdMin: `(min-width: 0`,
 lgMin: `(min-width: 0`,
 xlMin: `(min-width: 0`,
 xsMax: `(max-width: 0`,
 smMax: `(max-width: 0`,
 mdMax: `(max-width: 0`,
 lgMax: `(max-width: 0`,
 xlMax: `(max-width: 0`,
 motion: '(prefers-reduced-motion)',
 safari: 'not all and (min-resolution:.001dpcm)',
 hover: '(any-hover: hover)',
 dark: '(prefers-color-scheme: dark)',
 light: '(prefers-color-scheme: light)'
};
